### PR TITLE
Remove redundant build flags

### PR DESCRIPTION
**Pull request by Erick555**
The 3.30 runtime sets these as defaults.

### CODE REVIEW

**Comment by TingPing** [comment]
Well it doesn't have `V=1`. Just to make this easier all of your PRs should not remove that.

**Comment by Erick555** [comment]
Sure, however it looks like copy-paste to me rather than something intentional. Some gnome apps use it, others not. I wondered if I should leave that and decided that nobody would care anyway.

If you think it's valuable then I can re-add it.

**Comment by TingPing** [comment]
While I agree it is still a behavior change and I will gladly just merge away for non-behavior changing PRs.

**Comment by Erick555** [comment]
I will re-add them in next hour, stay tuned! :smile:

**Pull request closed without merging**
